### PR TITLE
Add mypy check to github actions

### PR DESCRIPTION
**Pull request by ooigavin**
Fixes # 166

Changes proposed in this PR:
- Add type checking in github actions using mypy 
- Improve type hinting in the code

### CODE REVIEW

**Comment by ooigavin** [comment]
Hi @avara1986  I have added the mypy checks into github actions, still working on reducing the errors & adding more type hints. However I have some questions regarding the pipfile and the lock file. Not too familiar with it as I normally use pip & virtualenv in my own projects. But I do understand the concept of a lock file from other package managers like yarn.

When I generated the lockfile I see that not only did i add the mypy dependency, I also upgraded the minor versions of other dependencies (which should be non-breaking). But whaat I would like to ask is what the `markers` do in the lockfile, cause I noticed that regenerating the lockfile added a few of these markers.

My python env is 3.7.5

**Comment by ooigavin** [comment]
Goddit, thanks! one other thing I wanted to check, I am used to creating small commits for each change i make. However sometimes I think maintainers prefer PRs to contain a single commit? Not sure what is the convention for this project.

**Comment by avara1986** [comment]
IMHO, i like both. One big PR or a lot of small PRs :smiley: BUT, if you are playing the [Hacktoberfest](https://hacktoberfest.digitalocean.com/details) I think a lot of small PRs with one or two lines updated could be considered as SPAM :+1:

**Comment by ooigavin** [comment]
oh what i meant is in a single PR, is it alright if it contains many commits, or should it just contain one commit containing all the changes? Only intend to submit a single PR for this

**Comment by avara1986** [comment]
I read that i want sorry....:joy: No, you can do all commits that you want, It's ok 1 or 1000 :+1:

**Comment by ooigavin** [comment]
Have added more type hints and reduced some of the mypy errors, left some whr I wasnt too sure about the typing alone.

**Comment by avara1986** [comment]
Great PR @ooigavin ! is ready to review and merge or you want to add more commits? :+1:

**Comment by ooigavin** [comment]
I've looked thru most of the codebase, and added the types whr I was confident to add them. I'm ready to merge, unless you need me to make any changes?

**Review by avara1986 — APPROVED** [review]

**Pull request merged**
